In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib

dataf = pd.read_csv('music.csv')
x = dataf.drop(columns = ['genre'])
y = dataf['genre']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)



model1 = DecisionTreeClassifier()
model1.fit(x_train,y_train)
#pred1 = model1.predict([[21,1],[28,0]])
# pred1 = model1.predict(pd.DataFrame(x_test, columns=x.columns))
# acc = accuracy_score(y_test,pred1)
# acc
joblib.dump(model1,'music_rec.joblib')

AttributeError: module 'joblib' has no attribute 'dum'

In [33]:
dataf

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical